# pod distribution budget hoga

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fastapi-pdb
spec:
  minAvailable: 2               # min pods 2 available honge at a time 
  selector:
    matchLabels:
      app: fastapi